#include "init.h"
void RCC_Init(void)
{
   MODIFY_REG(RCC->CR,RCC_CR_HSITRIM, 0x80U);
   CLEAR_REG(RCC->CFGR);
   while(READ_BIT(RCC->CFGR,RCC_CFGR_SWS) != RESET);
   CLEAR_BIT(RCC->CR, RCC_CR_PLLON);
   while(READ_BIT(RCC->CR, RCC_CR_PLLRDY) != RESET);
   CLEAR_BIT(RCC->CR, RCC_CR_HSEON | RCC_CR_CSSON);
   while (READ_BIT(RCC->CR, RCC_CR_HSERDY) != RESET);
   CLEAR_BIT(RCC->CR,RCC_CR_HSEBYP);
   
   SET_BIT(RCC->CR, RCC_CR_HSEON);
   while(READ_BIT(RCC->CR, RCC_CR_HSERDY) == RESET);
   CLEAR_BIT(RCC->CR, RCC_CR_HSEBYP);
   SET_BIT(RCC->CR, RCC_CR_CSSON);

   CLEAR_REG(RCC->PLLCFGR);
   SET_BIT(RCC->PLLCFGR, RCC_PLLCFGR_PLLSRC_HSE);
   MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLM, RCC_PLLCFGR_PLLM_2);
   MODIFY_REG(RCC->PLLCFGR,RCC_PLLCFGR_PLLN_Msk, RCC_PLLCFGR_PLLN_2 | RCC_PLLCFGR_PLLN_4 | 
    RCC_PLLCFGR_PLLN_5 | RCC_PLLCFGR_PLLN_7);
   CLEAR_BIT(RCC->PLLCFGR,RCC_PLLCFGR_PLLP_Msk);
   SET_BIT(RCC->CR, RCC_CR_PLLON);
   while(READ_BIT(RCC->CR, RCC_CR_PLLRDY));

   MODIFY_REG(RCC->CFGR, RCC_CFGR_SW, RCC_CFGR_SW_PLL);
   MODIFY_REG(RCC->CFGR, RCC_CFGR_HPRE, RCC_CFGR_HPRE_DIV1);
   MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE1, RCC_CFGR_PPRE1_DIV4);
   MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE2, RCC_CFGR_PPRE2_DIV2);
   MODIFY_REG(RCC->CFGR, RCC_CFGR_MCO2PRE, RCC_CFGR_MCO2PRE_Msk);
   CLEAR_BIT(RCC->CFGR, RCC_CFGR_MCO2);
   MODIFY_REG(FLASH->ACR, FLASH_ACR_LATENCY, FLASH_ACR_LATENCY_5WS);
}
void GPIO_Init(void)
{
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN);    // GPIOB clock enable [file:21]
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE0_0);     // PB0: Output mode [file:21]
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT0);     // PB0: Push‑Pull [file:21]
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0); // PB0: medium speed [file:21]
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR0_0 | GPIO_PUPDR_PUPDR0_1); // PB0: no 

    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE7_0);     // PB7: Output mode [file:21]
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT7);     // PB7: Push‑Pull [file:21]
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_0); // PB7: medium speed [file:21]
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR7_0 | GPIO_PUPDR_PUPDR7_1); // PB7: no 

    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE14_0);     // PB14: Output mode [file:21]
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT14);     // PB14: Push‑Pull [file:21]
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR14_0); // PB14: medium speed [file:21]
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR14_0 | GPIO_PUPDR_PUPDR14_1); // PB14: no 

    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN);    // GPIOD clock enable [file:21]
    SET_BIT(GPIOD->MODER, GPIO_MODER_MODE0_0);     // PD0: Output mode [file:21]
    CLEAR_BIT(GPIOD->OTYPER, GPIO_OTYPER_OT0);     // PD0: Push‑Pull [file:21]
    SET_BIT(GPIOD->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0); // PD0: medium speed [file:21]
    CLEAR_BIT(GPIOD->PUPDR, GPIO_PUPDR_PUPDR0_0 | GPIO_PUPDR_PUPDR0_1); // PD0: no 

    SET_BIT(GPIOD->MODER, GPIO_MODER_MODE1_0);     // PD1: Output mode [file:21]
    CLEAR_BIT(GPIOD->OTYPER, GPIO_OTYPER_OT1);     // PD1: Push‑Pull [file:21]
    SET_BIT(GPIOD->OSPEEDR, GPIO_OSPEEDER_OSPEEDR1_0); // PD1: medium speed [file:21]
    CLEAR_BIT(GPIOD->PUPDR, GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR1_1); // PD1: no 

    SET_BIT(GPIOD->MODER, GPIO_MODER_MODE2_0);     // PD2: Output mode [file:21]
    CLEAR_BIT(GPIOD->OTYPER, GPIO_OTYPER_OT2);     // PD2: Push‑Pull [file:21]
    SET_BIT(GPIOD->OSPEEDR, GPIO_OSPEEDER_OSPEEDR2_0); // PD2: medium speed [file:21]
    CLEAR_BIT(GPIOD->PUPDR, GPIO_PUPDR_PUPDR2_0 | GPIO_PUPDR_PUPDR2_1); // PD2: no 

    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE13); // 00 = input [file:21]

    // PC13 no pull (на NUCLEO внешняя подтяжка уже есть)
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPD13); // 00 = no pull
}